import streamlit as st
import pandas as pd
import plotly.express as px
from collections import Counter

# Import our custom data loader
from data_loader import load_analyzed_reviews, load_product_insights

# --- Page Config ---
st.set_page_config(
    page_title="App Review Insights Dashboard",
    page_icon="📊",
    layout="wide"
)

# --- Load Data ---
@st.cache_data(ttl=10)
def load_data():
    reviews_df = load_analyzed_reviews()
    insights_df = load_product_insights()
    return reviews_df, insights_df

reviews_df, insights_df = load_data()

# --- Header Section ---
st.title("📊 Spotify Review Discovery Dashboard")
st.markdown("An AI-powered dashboard visualizing user feedback, sentiment, and automated executive insights.")

# Top-level metrics
col1, col2, col3 = st.columns(3)
with col1:
    st.metric("Total Reviews Analyzed", f"{len(reviews_df):,}")
with col2:
    platforms = reviews_df['source'].nunique() if not reviews_df.empty else 0
    st.metric("Platforms Tracked", platforms)
with col3:
    if not insights_df.empty:
        st.metric("AI Generated Insights", len(insights_df))
    else:
        st.metric("AI Generated Insights", "0")

st.divider()

# --- Main Visualizations ---
if not reviews_df.empty:
    col_chart1, col_chart2 = st.columns(2)
    
    with col_chart1:
        st.subheader("Sentiment Distribution")
        # Ensure we only count valid sentiments
        sentiment_counts = reviews_df['sentiment'].dropna().value_counts().reset_index()
        sentiment_counts.columns = ['Sentiment', 'Count']
        
        # Distinct color mapping for every sentiment
        color_discrete_map = {
            'Delighted': '#FFD700',   # Gold
            'Positive': '#00CC96',    # Green
            'Neutral': '#636EFA',     # Blue
            'Negative': '#FFA15A',    # Orange
            'Frustrated': '#EF553B'   # Red
        }
        
        fig = px.pie(
            sentiment_counts, 
            values='Count', 
            names='Sentiment', 
            hole=0.4,
            color='Sentiment',
            color_discrete_map=color_discrete_map
        )
        st.plotly_chart(fig, use_container_width=True)
        
    with col_chart2:
        st.subheader("Top Feature Mentions & Themes")
        
        # Extract and count all themes
        all_themes = []
        for theme_list in reviews_df['themes'].dropna():
            if isinstance(theme_list, list):
                all_themes.extend([t.strip().title() for t in theme_list if t])
                
        theme_counts = Counter(all_themes)
        top_themes = pd.DataFrame(theme_counts.most_common(10), columns=['Theme', 'Mentions'])
        
        fig = px.bar(
            top_themes, 
            x='Mentions', 
            y='Theme', 
            orientation='h',
            color='Mentions',
            color_continuous_scale='Blues'
        )
        fig.update_layout(yaxis={'categoryorder':'total ascending'})
        st.plotly_chart(fig, use_container_width=True)

st.divider()

# --- Executive AI Insights ---
st.subheader("🤖 Executive Summary Insights")
st.markdown("These insights were automatically synthesized by the Groq LLM based on clustered review themes.")

if not insights_df.empty:
    # Display insights in a 2-row by 5-column grid
    cols = st.columns(5)
    for idx, row in insights_df.iterrows():
        col = cols[idx % 5]
        with col:
            # Use a fixed-height container to ensure all boxes are exactly the same size
            with st.container(height=300, border=True):
                st.markdown(f"**{row['theme_name']}**")
                st.info(row['insight_summary'])
                st.caption("Generated by llama-3.3-70b-versatile.")
else:
    st.warning("No AI insights generated yet. (API rate limit may have prevented generation in Phase 4).")

st.divider()

# --- Semantic Search ---
st.subheader("🤖 Semantic Search")
st.markdown("Ask natural language questions (e.g., 'Why do users dislike the ads?') to find relevant reviews.")

with st.spinner("Loading AI Embedding Model (takes ~30s on first boot)..."):
    from semantic_search import SemanticSearcher
    if not reviews_df.empty:
        searcher = SemanticSearcher(reviews_df)

if 'search_query' not in st.session_state:
    st.session_state.search_query = ""

def clear_search():
    st.session_state.search_query = ""

st.markdown("**Ask a question about the user feedback:**")
col1, col2, col3 = st.columns([6, 1, 1])
with col1:
    query = st.text_input("Ask a question about the user feedback:", key="search_query", label_visibility="collapsed")
with col2:
    submit_button = st.button("Search", type="primary", use_container_width=True)
with col3:
    st.button("Clear", on_click=clear_search, use_container_width=True)

# This allows the search to trigger EITHER when clicking the 'Search' button 
# OR when pressing 'Enter' in the text field (which automatically reruns the script with the query)
if query:
    # Prevent unnecessary API calls by caching the last query's answer in session_state
    if 'last_query' not in st.session_state:
        st.session_state.last_query = ""
    if 'last_answer' not in st.session_state:
        st.session_state.last_answer = ""
    if 'last_results' not in st.session_state:
        st.session_state.last_results = []
        
    if query != st.session_state.last_query:
        results = searcher.search(query, top_k=50)
        
        if not results:
            ai_answer = "No highly relevant reviews found for that query."
        else:
            with st.spinner("🤖 AI is reading the reviews to answer your question..."):
                import os
                from dotenv import load_dotenv
                load_dotenv()
                
                api_keys = []
                for k, v in os.environ.items():
                    if k.startswith("GROQ_API_KEY_") and v:
                        api_keys.append(v)
                if not api_keys and os.getenv("GROQ_API_KEY"):
                    api_keys.append(os.getenv("GROQ_API_KEY"))
                    
                ai_answer = searcher.answer_question(query, results, api_keys)
                
        # Save to state
        st.session_state.last_query = query
        st.session_state.last_answer = ai_answer
        st.session_state.last_results = results
    else:
        # Load from state if query hasn't changed
        results = st.session_state.last_results
        ai_answer = st.session_state.last_answer
    
    if not results:
        st.warning("No highly relevant reviews found for that query.")
    else:
        st.success(f"**AI Answer:** {ai_answer}")
        
        # Only show the evidence if the AI was actually able to answer the question
        if "I cannot answer this" not in ai_answer:
            with st.expander(f"Evidence (Top {len(results)} Semantically Relevant Reviews)", expanded=False):
                for idx, row in pd.DataFrame(results).iterrows():
                    st.caption(f"Score: {row['score']}% | Sentiment: {row['sentiment']}")
                    st.info(f'"{row["text"]}"')

st.divider()

# --- Raw Data Explorer ---
st.subheader("🔍 Raw Data Explorer")
st.markdown(f"Filter and explore the {len(reviews_df):,} analyzed reviews to verify AI accuracy.")

# Simple filtering for the table
col_filter1, col_filter2 = st.columns(2)
with col_filter1:
    search_term = st.text_input("Search reviews by keyword or theme:", "")
with col_filter2:
    sentiment_filter = st.multiselect("Filter by Sentiment:", options=reviews_df['sentiment'].dropna().unique())

filtered_df = reviews_df.copy()

if search_term:
    text_match = filtered_df['cleaned_text'].str.contains(search_term, case=False, na=False)
    # Convert the themes list to a string so we can easily search inside it
    theme_match = filtered_df['themes'].astype(str).str.contains(search_term, case=False, na=False)
    filtered_df = filtered_df[text_match | theme_match]
    
if sentiment_filter:
    filtered_df = filtered_df[filtered_df['sentiment'].isin(sentiment_filter)]

st.dataframe(
    filtered_df[['date', 'source', 'sentiment', 'cleaned_text', 'themes']], 
    use_container_width=True,
    hide_index=True
)
